# Generated by Django 3.0.5 on 2020-06-13 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20200610_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bespoke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name1', models.CharField(blank=True, max_length=50)),
                ('person_name2', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateField(blank=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=50)),
                ('birth_weight_lb', models.IntegerField(blank=True)),
                ('birth_weight_oz', models.IntegerField(blank=True)),
                ('wedding_date', models.DateField(blank=True)),
                ('address_line1', models.CharField(blank=True, max_length=50)),
                ('is_complete', models.BooleanField(default=False)),
                ('bespoke_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.OrderItem')),
            ],
            options={
                'verbose_name_plural': 'Bespoke',
            },
        ),
    ]
