# Generated by Django 3.0.5 on 2020-06-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_bespoke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bespoke',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
