# Generated by Django 3.0.5 on 2020-06-05 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20200605_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_total',
            field=models.DecimalField(decimal_places=2, default=None, editable=False, max_digits=8),
            preserve_default=False,
        ),
    ]
 