# Generated by Django 3.0.5 on 2020-06-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_orderitem_item_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=8),
            preserve_default=False,
        ),
    ]
