# Generated by Django 3.0.5 on 2020-06-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20200614_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bespoke',
            name='address_line1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bespoke',
            name='birth_weight_lb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bespoke',
            name='birth_weight_oz',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bespoke',
            name='person_name1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bespoke',
            name='person_name2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bespoke',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bespoke',
            name='wedding_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
