# Generated by Django 3.0.5 on 2020-06-14 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20200614_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bespoke',
            old_name='bespoke_item',
            new_name='bespoke_order',
        ),
    ]
