# Generated by Django 3.0.5 on 2020-06-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_bespoke_bespoke_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bespoke',
            name='bespoke_product',
        ),
    ]
