# Generated by Django 3.0.5 on 2020-06-14 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200614_1958'),
        ('checkout', '0010_remove_bespoke_bespoke_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='bespoke',
            name='bespoke_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Products'),
            preserve_default=False,
        ),
    ]
