# Generated by Django 3.0.5 on 2020-06-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200613_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='testimonial',
            field=models.TextField(max_length=300),
        ),
    ]
