# Generated by Django 3.0.5 on 2020-06-10 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('Cards', 'Cards'), ('Cake', 'Cake Toppers'), ('Gifts', 'Gifts')], max_length=100)),
                ('image', models.ImageField(upload_to='img')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('B', 'Birthday'), ('W', 'Wedding'), ('A', 'Anniversary'), ('H', 'New Home'), ('BB', 'Baby')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('size', models.CharField(choices=[('A4', 'A4'), ('A5', 'A5')], max_length=100)),
                ('label', models.CharField(choices=[('New', 'New'), ('Sale', 'Sale')], max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('is_bespoke', models.BooleanField()),
                ('is_active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_anonymous', models.BooleanField(default=False)),
                ('review_text', models.TextField()),
                ('review_rating', models.IntegerField()),
                ('review_date', models.DateField()),
                ('review_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product Reviews',
            },
        ),
    ]
