# Generated by Django 3.0.5 on 2020-05-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('B', 'Birthday'), ('W', 'Wedding'), ('A', 'Anniversary'), ('H', 'New Home'), ('BB', 'Baby')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('size', models.CharField(choices=[('A4', 'A4'), ('A5', 'A5')], max_length=100)),
                ('label', models.CharField(choices=[('New', 'New'), ('Sale', 'Sale')], max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('is_bespoke', models.BooleanField()),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
