# Generated by Django 3.0.5 on 2020-05-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200518_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_type',
            field=models.CharField(choices=[('Cards', 'Cards'), ('Cake', 'Cake Toppers'), ('Gifts', 'Gifts')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
