# Generated by Django 3.0.5 on 2020-06-04 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productreviews_user_anonymous'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreviews',
            options={'verbose_name_plural': 'Product Reviews'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
