# Generated by Django 3.0.5 on 2020-06-15 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200614_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='review_rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
