# Generated by Django 3.0.5 on 2020-06-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200615_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='colour',
            field=models.CharField(blank=True, choices=[('gold', 'Gold'), ('rose-gold', 'Rose Gold'), ('silver-glitter', 'Silver Glitter')], max_length=50),
        ),
    ]
