# Generated by Django 3.0.5 on 2020-06-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200618_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='review_active',
            field=models.BooleanField(default=True),
        ),
    ]
