# Generated by Django 3.0.5 on 2020-06-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200618_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='static/img/TartanThomDefault.jpg', upload_to='img'),
        ),
    ]
