# Generated by Django 3.0.5 on 2020-06-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200619_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='colour',
        ),
    ]
