# Generated by Django 3.0.5 on 2020-06-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200619_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='review_text',
            field=models.TextField(max_length=300),
        ),
    ]
